# Generated by Django 4.2.6 on 2023-11-11 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_order_product_thumbnail_alter_product_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="merchant_id", new_name="payment_intent",
        ),
    ]
